name: $(Date:yyyy.MM.dd.HHmm)

resources:
  containers:
  - container: dotnet
    image: microsoft/dotnet:latest

jobs:
- job: windows
  displayName: Build and Test Windows
  pool:
    vmImage: vs2017-win2016
  steps:
    - template: build/windows/build.yml

- job: linux
  displayName: Build and Test Linux
  pool:
    vmImage: Ubuntu 16.04
  container: dotnet
  steps:
    - template: build/linux/build.yml

- job: macos
  displayName: Build and Test MacOS
  pool:
    vmImage: macOS 10.13
  steps:
    - template: build/macos/build.yml
