on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  contents: read

name: main
jobs:

  linux:
    name: Linux
    runs-on: ubuntu-24.04
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: dotnet build -f net8.0 -c Release
        working-directory: tests/QRCodeCore.Tests

      - name: Test
        run: dotnet test -f net8.0 -c Release
        working-directory: tests/QRCodeCore.Tests

  macos:
    name: MacOS
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: dotnet build -f net8.0 -c Release
        working-directory: tests/QRCodeCore.Tests

      - name: Test
        run: dotnet test -f net8.0 -c Release
        working-directory: tests/QRCodeCore.Tests

  windows:
    name: Windows
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: dotnet build -c Release
        working-directory: tests/QRCodeCore.Tests

      - name: Test
        run: dotnet test -c Release
        working-directory: tests/QRCodeCore.Tests
