on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: main
jobs:

  linux:
    name: 'Linux'
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Build
      run: dotnet build -f net6 -c Release
      working-directory: tests/QRCodeCore.Tests

    - name: Test
      run: dotnet test -f net6 -c Release
      working-directory: tests/QRCodeCore.Tests

  macos:
    name: 'MacOS'
    runs-on: macos-11

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Build
      run: dotnet build -f net6 -c Release
      working-directory: tests/QRCodeCore.Tests

    - name: Test
      run: dotnet test -f net6 -c Release
      working-directory: tests/QRCodeCore.Tests

  windows:
    name: 'Windows'
    runs-on: windows-2022

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: dotnet build -c Release
      working-directory: tests/QRCodeCore.Tests

    - name: Test
      run: dotnet test -c Release
      working-directory: tests/QRCodeCore.Tests
